# Generated by Django 5.1.2 on 2024-11-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_title_recipe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipebookrecipe',
            name='added_by',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
